### ISSUE TITLE
Leveling functions

### ISSUE THREAD

**Issue by buched** [ANYCUBIC-3D/ANYCUBIC_CHIRON#1]
Leveling functions with this version not work

**Comment by ANYCUBIC-3D** [comment]
Hello there,
please use Cura  print interface send M1001 to active auto leveling funciton.
Or you could create a txt file, input
M140 S0
M104 S0
M1001
then save and rename filename as 'Auto_leveling.gcode',copy this file to SD card,print it from 'PRINT' menu to active auto leveling.

Manual leveling like below:
M140 S0
M104 S0
M1000

If manual leveling function active, auto leveling will unavailable.
